version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - <data-directory>:/var/lib/postgresql/data
    env_file:
      - env-postgres.list